print('Qual eh o seu nome')
nome = input()
print('Ola ' + nome + ' Qual a sua idade' )
idade = input()
print(str(idade) + ' legal qual o seu sexo ')
sexo = input()
print('sexo: ' + sexo + ' Qual a sua cidade')
cidade = input()
print('Em qual estado fica ' + cidade )
estado = input()
print('Legal então ' + cidade + ' fica em ' + estado  + ' agora informe o seu estado civil' )
estado_civil = input()
print('confirmando os dados informados : '  + nome + ' voce tem  ' + str(idade) + '  eh do sexo ' + sexo + ' sua cidade eh: '  + cidade + ' que fica no estado de ' + estado + ' e seu estado civil eh ' + estado_civil)
