print('Qual eh o seu nome ')
nome = input()
print('Ola %s  Qual a sua idade ' % nome )
idade = input()
print(str(idade) + ' legal qual o seu sexo ')
sexo = input()
print('sexo: %s  Qual a sua cidade ' % sexo )
cidade = input()
print('Em qual estado fica  %s'  % cidade )
estado = input()
print('Legal então  %s  fica em %s agora informe o seu estado civil ' %(cidade, estado))
estado_civil = input()
#print('confirmando os dados informados : %s  voce tem  ' + str(idade) + '  eh do sexo %s  sua cidade eh: %s  que fica no estado de %s  e seu estado civil eh %s ' (nome, sexo, cidade, estado, estado_civil))
